# Generated by Django 4.1.5 on 2023-01-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('diretor', models.CharField(max_length=100)),
                ('ano_lancamento', models.IntegerField(max_length=4)),
                ('nota', models.CharField(choices=[('1', 'Muito Ruim'), ('2', 'Ruim'), ('3', 'Aceitavel'), ('4', 'Bom'), ('5', 'Muito Bom')], max_length=1)),
            ],
        ),
    ]
