# Generated by Django 4.1.5 on 2023-01-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='ano_lancamento',
            field=models.CharField(max_length=4),
        ),
    ]
